#!/usr/bin/env bash

# Update the system
sudo apt-get -y  update

# Install Nginx
sudo apt-get install -y nginx

# Create a new server block configuration for the redirection
cat <<EOF > /etc/nginx/sites-available/redirect
server {
    listen 80;
    server_name olecko.tech;

    location /redirect_me {
        return 301 https://www.twitter.com/realmc_paul;
    }

    location / {
        return 404;
    }
}
EOF

# Enable the new server block
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove default Nginx server block
rm /etc/nginx/sites-enabled/default

# Test Nginx configuration
nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart
